export enum PlanStatus {
	ACTIVE = "ACTIVE",
	COMPLETED = "COMPLETED",
	ARCHIVED = "ARCHIVED",
}

export enum DailyStatus {
	COMPLETED = "COMPLETED",
	PARTIAL = "PARTIAL",
	MISSED = "MISSED",
}

export enum MilestoneStatus {
	PENDING = "PENDING",
	IN_PROGRESS = "IN_PROGRESS",
	COMPLETED = "COMPLETED",
	MISSED = "MISSED",
}

export enum QuestionType {
	MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
	TRUE_FALSE = "TRUE_FALSE",
	SHORT_ANSWER = "SHORT_ANSWER",
}
